changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.spec.{js,ts,tsx}'

packageExtensions:
  alex@*:
    dependencies:
      'supports-color': '^7.2.0'
  gatsby@*:
    dependencies:
      '@babel/types': ^7.12.0
      babel-plugin-styled-components: ^1.11.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.3.3.cjs
